version: 4
shared:
  environment:
    CHANGELOG_FILENAME: docs/changelog.md
    PACKAGE_DIRECTORY: serviceping
    
jobs:
  validate_test:
    template: python-2104/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python-2104/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python-2104/validate_style
    requires: [~commit, ~pr]

  validate_deps:
    template: python/validate_dependencies
    requires: [~commit, ~pr]
    
  validate_security:
    template: python-2104/validate_security
    requires: [~commit, ~pr]

  validate_documentation:
    template: python-2104/documentation
    requires: [~commit, ~pr]

  validate_package:
    template: python-2104/package_python
    requires: [~commit, ~pr]

  generate_version:
    template: python-2104/version
    requires: [validate_test, validate_lint, validate_codestyle, validate_deps, validate_security]
  
  publish_test_pypi:
    template: python-2104/package_python
    environment:
      PACKAGE_TAG: False
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
        PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]

  publish_pypi:
    template: python-2104/package_python
    requires: [verify_test_package]

  publish_documentation:
    template: python-2104/documentation
    requires: [publish_pypi]
